# Project #2: Automation of Concrete Mix Design (NDOT)
**Team:** Gabriela Gonzalez Ng, Lily Strohl, Rebecca Carroll  
**Date:** 02/20/2026

**Client:** Nebraska Department of Transportation (NDOT)

---

## Project Context (Client Summary)
NDOT has requested a Python-based automation of its Excel “Mix Design” worksheet logic. The workflow must:
1) translate Excel logic into Python functions,  
2) prompt the user for inputs sequentially (mirroring Excel order),  
3) generate a client-readable weight chart for **one cubic yard**, and  
4) evaluate **four realistic mix scenarios** as basic verification/validation. 
---

## Deliverables Checklist 
- [ ] Excel logic replicated using **major calculation functions**  
- [ ] **Sequential user prompts** implemented 
- [ ] **Final weight chart** for 1 yd³ generated and formatted  
- [ ] **4 mix scenarios** documented + run through the model  
- [ ] Scenario outputs compared (quick verification/validation narrative)

---

# Part 1 - Setup

## 1.1 Imports and Global Settings
▶️ **Code Cell:** imports (numpy/pandas), formatting helpers, constants

- Units convention:
  - Cement, water, aggregates: **lb/yd³**
  - Specific gravity: dimensionless
  - Air content: %
  - w/c ratio: dimensionless

---

## 1.2 Assumptions and Constants
▶️ **Code Cell:** define constants (e.g., density of water, unit conversions, etc.)

Document assumptions here:
- <Assumption 1>
- <Assumption 2>

---

In [2]:
#Importing packages

import pandas as pd
import numpy as np
from dataclasses import dataclass
from IPython.display import display

In [3]:
# Define the fundamental constants used throughout the mix design

cubic_yard_ft3 = 27 # cubic feet in one cubic yard
unit_weight_water = 62.4 #lb/ft^3 (unit weight of water)

## 1.3 Inputs Dictionary 
▶️ **Code Cell:** create a dictionary or dataclass for all inputs

Recommended structure:
- cement_A = "what does this variable mean"
- any additional parameters from the Excel logic you are replicating
---

In [4]:
@dataclass
class MixDesignInputs:
    # Project metadata
    project_no: int
    control_no: int
    concrete_class: str

    # Cementitious materials (lb/yd^3)
    cement_A: float
    fly_ash_B: float
    silica_fume_C: float
    other_scm_D: float

    # Mix properties
    wc_ratio_E: float
    air_content_F: float

    # Aggregate percentages
    G_percent_fine_aggregate: float
    H_percent_coarse_aggregate: float
    I_percent_other_aggregate: float

    # Specific gravities
    sg_cement_J: float
    sg_fly_ash_K: float
    sg_silica_fume_L: float
    sg_other_scm_M: float
    N_specific_gravity: float
    O_specific_gravity: float
    P_specific_gravity: float

# Part 2 - Cement Calculation Function

For each function below:
- State **inputs**
- State **outputs**
- Include a short note: "about what the function does”

---

## 1. Function Q: Water Weight (lb/yd³)
▶️ **Code Cell:** define `calc_water_weight(...)`

**Inputs:**
- cement content
- w/c ratio
- (<any modifiers from Excel>)

**Output:**
- water weight (lb/yd³)

---

In [5]:
def calculate_water_weight_Q(cement_A, fly_ash_B, silica_fume_C, other_scm_D, wc_ratio_E):
    total_cementitious = cement_A + fly_ash_B + silica_fume_C + other_scm_D
    water_weight_Q = total_cementitious * wc_ratio_E
    return water_weight_Q

## 2. Function R: Cement Volume (ft³)
▶️ **Code Cell:** define `calculate_volume_R(...)`

**Inputs:**
- weight of cement A
- Specific gravity J
- Unit Weight of water
  
**Output:**
- Cement Volume R (ft³)

---

In [6]:
def calculate_volume_R(cement_A, sg_cement_J):
    volume_R = cement_A / (sg_cement_J * unit_weight_water)
    return volume_R

## 3. Function S: Fly Ash Volume (ft³)
▶️ **Code Cell:** define `calculate_volume_S(...)`

**Inputs:**
- weight of Fly Ash B
- Specific gravity K
- Unit Weight of water
  
**Output:**
- Cement Volume S (ft³)

---

In [7]:
def calculate_volume_S(fly_ash_B, sg_fly_ash_K):
    volume_S = fly_ash_B / (sg_fly_ash_K * unit_weight_water)
    return volume_S

## 4. Function T: Silica Fume Volume (ft³)
▶️ **Code Cell:** define `calculate_volume_T(...)`

**Inputs:**
- weight of Silica Fume C
- Specific gravity L
- Unit Weight of water
  
**Output:**
- Cement Volume T (ft³)

---

In [8]:
def calculate_volume_T(silica_fume_C, sg_silica_fume_L):
    volume_T = silica_fume_C / (sg_silica_fume_L * unit_weight_water)
    return volume_T

## 5. Function U: Other SCM Volume (ft³)
▶️ **Code Cell:** define `calculate_volume_R(...)`

**Inputs:**
- weight of other SCM D
- Specific gravity M
- Unit Weight of water
  
**Output:**
- Cement Volume U (ft³)

---

In [9]:
def calculate_volume_U(other_scm_D, sg_other_scm_M):
    return other_scm_D / (sg_other_scm_M * unit_weight_water)

## 6. Function V: Air Volume (ft³)
▶️ **Code Cell:** define `calculate_volume_V(...)`

**Inputs:**
- Target air content F
- total volume of 1 cubic yard
  
**Output:**
- Air Volume V (ft³)

---

In [10]:
def calculate_air_volume_V(target_air_content_F):
    volume_V = (target_air_content_F/100) * cubic_yard_ft3
    return volume_V

## 7. Function W: Water Volume (ft³)
▶️ **Code Cell:** define `calculate_volume_W(...)`

**Inputs:**
- Weight of water Q
- unit weight of water
  
**Output:**
- Water Volume W (ft³)

---

In [11]:
def calculate_water_volume_W(water_weight_Q):
    volume_W = water_weight_Q / unit_weight_water
    return volume_W

## 8. Function X: Total Aggregate Volume (ft³)
▶️ **Code Cell:** define `calculate_volume_W(...)`

**Inputs:**
- total volume of 1 cubic yard
- Cemetitious material volumes (R,S,T,U)
- air volume V
- water volume W
  
**Output:**
- Total Aggregate Volume (ft³)

---

In [12]:
def calculate_total_aggregate_volume_X(R_cement, S_cement, T_cement, U_cement, V_air_volume, W_water_volume):
    volume_x = cubic_yard_ft3 - R_cement - S_cement - T_cement - U_cement - V_air_volume - W_water_volume
    return volume_x

## 9. Function Y: Fine Aggregate Weight (lb)
▶️ **Code Cell:** define `calculate_fine_aggregate_weight_Y(...)`

**Inputs:**
- target percent fine aggregate G
- specific gravity of fine aggregate N
- total aggregate volume X
- unit weight of water
  
**Output:**
- Fine Aggregate Weight (lb)

---

In [13]:
def calculate_fine_aggregate_weight_Y(G_percent_fine_aggregate, N_specific_gravity, X_total_aggregate_volume):
    volume_y = unit_weight_water * (G_percent_fine_aggregate/100) * N_specific_gravity * X_total_aggregate_volume
    return volume_y

## 10. Function Z: Coarse Aggregate Weight (lb)
▶️ **Code Cell:** define `calculate_coarse_aggregate_weight_Z(...)`

**Inputs:**
- target percent coarse aggregate H
- specific gravity of coarse aggregate O
- total aggregate volume X
- unit weight of water
  
**Output:**
- Coarse Aggregate Weight (lb)

---

In [14]:
def calculate_coarse_aggregate_weight_Z(H_percent_coarse_aggregate, O_specific_gravity, X_total_aggregate_volume):
    volume_z = unit_weight_water * (H_percent_coarse_aggregate/100) * O_specific_gravity * X_total_aggregate_volume
    return volume_z

## 11. Function AA: Other Aggregate Weight (lb)
▶️ **Code Cell:** define `calculate_other_aggregate_weight_AA(...)`

**Inputs:**
- target percent other aggregate I
- specific gravity of other aggregate P
- total aggregate volume X
- unit weight of water
  
**Output:**
- Other Aggregate Weight (lb)

---

In [15]:
def calculate_other_aggregate_weight_AA(I_percent_other_aggregate, P_specific_gravity, X_total_aggregate_volume):
    volume_AA = unit_weight_water * (I_percent_other_aggregate/100) * P_specific_gravity * X_total_aggregate_volume
    return volume_AA

# Part 3 - Sequential User Inputs 
**Planned prompt order:**
1. Project Number
2. Control Number
3. Concrete Class
4. Cement weight (lb/yd³)
5. Fly Ash weight (lb/yd³)
6. Silica Fume weight (lb/yd³)
7. Other SCM weight (lb/yd³)
8. Target Water–cement ratio
9. Air content (%)
10. Fine Aggregate (%)
11. Coarse Aggregate (%)
12. Other Aggregate (%)
13. Specific Gravity of Cement
14. Specific Gravity of Fly Ash
15. Specific Gravity of Silica Fume
16. Specific Gravity of Cement
17. Specific Gravity of Cement
18. Specific Gravity of Cement

# Part 4 - Running Complete Mix Design

Run your functions, output a table of the design (Lab #3 will show you how to do that)

In [16]:
# NDOT Concrete Mix Design – Full Integrated Run

def ndot_mix_design():

    print("\n=== NDOT Concrete Mix Design ===")
    # Project metadata
    project_no = int(input("Enter project number: "))
    control_no = int(input("Enter control number: "))
    concrete_class = input("Enter class of concrete: ")

    # Cementitious material inputs (lb per cubic yard)
    cement_A = float(input("Enter weight of cement per yd^3: "))
    fly_ash_B = float(input("Enter weight of fly ash per yd^3: "))
    silica_fume_C = float(input("Enter weight of silica fume per yd^3: "))
    other_scm_D = float(input("Enter weight of other SCM per yd^3: "))

    wc_ratio_E = float(input("Enter targer water/cement ratio: "))
    target_air_content_F = float(input("Enter targer % air content: "))


    # Aggregate proportions (%)
    G_percent_fine_aggregate = float(input("Enter targer % fine aggregate: "))
    H_percent_coarse_aggregate = float(input("Enter targer % coarse aggregate: "))
    I_percent_other_aggregate = float(input("Enter targer % other aggregate: "))

    # Specific gravities
    sg_cement_J = float(input("Enter specific gravity of cement J: "))
    sg_fly_ash_K = float(input("Enter specific gravity of cement K: "))
    sg_silica_fume_L = float(input("Enter specific gravity of cement L: "))
    sg_other_scm_M = float(input("Enter specific gravity of cement M: "))
    N_specific_gravity = float(input("Enter specific gravity of cement N: "))
    O_specific_gravity = float(input("Enter specific gravity of cement O: "))
    P_specific_gravity = float(input("Enter specific gravity of cement P: "))

    # Calculations
    Q = calculate_water_weight_Q(cement_A, fly_ash_B, silica_fume_C, other_scm_D, wc_ratio_E)

    R = calculate_volume_R(cement_A, sg_cement_J)
    S = calculate_volume_S(fly_ash_B, sg_fly_ash_K)
    T = calculate_volume_T(silica_fume_C, sg_silica_fume_L)
    U = calculate_volume_U(other_scm_D, sg_other_scm_M)

    V = calculate_air_volume_V(target_air_content_F)
    W = calculate_water_volume_W(Q)

    X = calculate_total_aggregate_volume_X(R, S, T, U, V, W)

    Y = calculate_fine_aggregate_weight_Y(G_percent_fine_aggregate, N_specific_gravity, X)
    Z = calculate_coarse_aggregate_weight_Z(H_percent_coarse_aggregate, O_specific_gravity, X)
    AA =  calculate_other_aggregate_weight_AA(I_percent_other_aggregate, P_specific_gravity, X)

    # Output: Final Weight Chart
    print("\n---------------------------------------------")
    print(" NDOT Concrete Mix Design – Weight Summary")
    print("         (1 Cubic Yard of Concrete)")

    print("---------------------------------------------")
    print(f"Project Number:       {project_no}")
    print(f"Class of Concrete:    {concrete_class}")
    print(f"Control Number:       {control_no}")
    print("---------------------------------------------")
    print(f"Cement (A):            {cement_A:8.1f} lb")
    print(f"Fly Ash (B):           {fly_ash_B:8.1f} lb")
    print(f"Silica Fume (C):       {silica_fume_C:8.1f} lb")
    print(f"Other SCM (D):         {other_scm_D:8.1f} lb")
    print("---------------------------------------------")
    print(f"Fine Aggregate (Y):    {Y:8.0f} lb")
    print(f"Coarse Aggregate (Z):  {Z:8.0f} lb")
    print(f"Other Aggregate (AA):  {AA:8.0f} lb")
    print("---------------------------------------------")
    print(f"Water (Q):             {Q:8.0f} lb")
    print("---------------------------------------------")
    print("End of Mix Design Summary")

    # ---- Prepare NDOT-style table ----
    components = [
        "Cement",
        "Water",
        "Fine Aggregate",
        "Coarse Aggregate",
        "Other Aggregate",
        "Air (volumetric)",
        "Total (sanity check)"
    ]

    weights = [
        round(cement_A, 1),
        round(Q, 1),
        round(Y, 1),
        round(Z, 1),
        round(AA, 1),
        f"{round(target_air_content_F, 1)} %",  # volumetric air
        round(cement_A + Q + Y + Z + AA, 1)
    ]

    notes = [
        "",  # Cement
        "",  # Water
        "",  # Fine Aggregate
        "",  # Coarse Aggregate
        "",  # Other Aggregate
        "percent / ft³",  # Air
        ""  # Total
    ]

    df_ndot = pd.DataFrame({
        "Component": components,
        "Weight (lb/yd³)": weights,
        "Notes": notes
    })

    # ---- Display NDOT-style table ----
    print(f"\nNDOT Concrete Mix Design – Full Summary (1 yd³ of Concrete)")
    print(f"Project Number: {project_no} | Class: {concrete_class} | Control No: {control_no}")
    print("-------------------------------------------------------------")
    display(df_ndot)

# Part 5 - Running Scenarios

For each scenario:
- Source citation (DOT doc / NDOT / engineering reference)
- Intended use case (e.g., pavement, bridge deck, cold weather)
- Input parameter set (must match your prompt model)

### Scenario 1: <Name>
- **Source:** <citation>
- **Use case:** <…>
- **Inputs:**
  - cement_content_lb_yd3 = …
  - wc_ratio = …
  - air_content_pct = …
  - sg_* = …
  - fine_agg_fraction = …
  - (<others>)


Suggested output table:

| Component | Weight (lb/yd³) | Notes |
|---|---:|---|
| Cement | <…> | |
| Water | <…> | |
| Fine Aggregate | <…> | |
| Coarse Aggregate | <…> | |
| Air (volumetric) | <…> | percent / ft³ |
| Total (sanity check) | <…> | |

Include:
- rounding rules (e.g., 1 decimal)
- clear units
- a short printed summary for a “client-readable” output

---

### Scenario 1: 47B
- **Source:** NDOT Pavement Design Manual
- **Use case:** concrete pavements, low-load concrete surfaces, approach slabs, tie-ins, shoulders, and general structural concrete
- **Inputs:**
  - cement_A (lb/ft^3)= 500
  - fly_ash_B (lb/ft^3) = 80
  - silica_fume_C (lb/ft^3) = 0
  - other_scm_D (lb/ft^3) = 0
  - wc_ratio_E = 0.44
  - target_air_content_F (%) = 6.5 
  - G_percent_fine_aggregate (%) = 40
  - H_percent_coarse_aggregate (%) = 60
  - I_percent_other_aggregate (%) = 0
  - sg_cement_J = 3.15
  - sg_fly_ash_K = 2.40
  - sg_silica_fume_L = 2.20
  - sg_other_scm_M = 2.80
  - N_specific_gravity = 2.65
  - O_specific_gravity = 2.70
  - P_specific_gravity = 2.70

In [52]:
ndot_mix_design()

=== NDOT Concrete Mix Design ===

Enter project number:  3
Enter control number:  1
Enter class of concrete:  47B
Enter weight of cement per yd^3:  500
Enter weight of fly ash per yd^3:  80
Enter weight of silica fume per yd^3:  0
Enter weight of other SCM per yd^3:  0
Enter targer water/cement ratio:  0.44
Enter targer % air content:  6.5
Enter targer % fine aggregate:  40
Enter targer % coarse aggregate:  60
Enter targer % other aggregate:  0
Enter specific gravity of cement J:  3.15
Enter specific gravity of cement K:  2.40
Enter specific gravity of cement L:  2.20
Enter specific gravity of cement M:  2.80
Enter specific gravity of cement N:  2.65
Enter specific gravity of cement O:  2.70
Enter specific gravity of cement P:  2.70

---------------------------------------------
 NDOT Concrete Mix Design – Weight Summary
         (1 Cubic Yard of Concrete)
---------------------------------------------
Project Number:       3
Class of Concrete:    47B
Control Number:       1
---------------------------------------------
Cement (A):               500.0 lb
Fly Ash (B):               80.0 lb
Silica Fume (C):            0.0 lb
Other SCM (D):              0.0 lb
---------------------------------------------
Fine Aggregate (Y):        1196 lb
Coarse Aggregate (Z):      1827 lb
Other Aggregate (AA):         0 lb
---------------------------------------------
Water (Q):                  255 lb
---------------------------------------------
End of Mix Design Summary

NDOT Concrete Mix Design – Full Summary (1 yd³ of Concrete)
Project Number: 3 | Class: 47B | Control No: 1
-------------------------------------------------------------

              Component Weight (lb/yd³)          Notes
0                Cement           500.0
1                 Water           255.2
2        Fine Aggregate          1195.7
3      Coarse Aggregate          1827.4
4       Other Aggregate             0.0
5      Air (volumetric)           6.5 %  percent / ft³
6  Total (sanity check)          3778.3

### Scenario 2: 47BD
- **Source:** NDOT Pavement Design Manual
- **Use case:** Bridge decks, approach slabs, diaphragm walls, rails, other higher-strength members
- **Inputs:**
  - cement_A (lb/ft^3)= 580
  - fly_ash_B (lb/ft^3) = 100
  - silica_fume_C (lb/ft^3) = 0
  - other_scm_D (lb/ft^3) = 0
  - wc_ratio_E = 0.44
  - target_air_content_F (%) = 6.5 
  - G_percent_fine_aggregate (%) = 40
  - H_percent_coarse_aggregate (%) = 60
  - I_percent_other_aggregate (%) = 0
  - sg_cement_J = 3.15
  - sg_fly_ash_K = 2.40
  - sg_silica_fume_L = 2.20
  - sg_other_scm_M = 2.80
  - N_specific_gravity = 2.65
  - O_specific_gravity = 2.70
  - P_specific_gravity = 2.70

In [53]:
ndot_mix_design()

=== NDOT Concrete Mix Design ===

Enter project number:  3
Enter control number:  2
Enter class of concrete:  47BD
Enter weight of cement per yd^3:  580
Enter weight of fly ash per yd^3:  100
Enter weight of silica fume per yd^3:  0
Enter weight of other SCM per yd^3:  0
Enter targer water/cement ratio:  0.44
Enter targer % air content:  6.5
Enter targer % fine aggregate:  40
Enter targer % coarse aggregate:  60
Enter targer % other aggregate:  0
Enter specific gravity of cement J:  3.15
Enter specific gravity of cement K:  2.40
Enter specific gravity of cement L:  2.20
Enter specific gravity of cement M:  2.80
Enter specific gravity of cement N:  2.65
Enter specific gravity of cement O:  2.70
Enter specific gravity of cement P:  2.70

---------------------------------------------
 NDOT Concrete Mix Design – Weight Summary
         (1 Cubic Yard of Concrete)
---------------------------------------------
Project Number:       3
Class of Concrete:    47BD
Control Number:       2
---------------------------------------------
Cement (A):               580.0 lb
Fly Ash (B):              100.0 lb
Silica Fume (C):            0.0 lb
Other SCM (D):              0.0 lb
---------------------------------------------
Fine Aggregate (Y):        1113 lb
Coarse Aggregate (Z):      1701 lb
Other Aggregate (AA):         0 lb
---------------------------------------------
Water (Q):                  299 lb
---------------------------------------------
End of Mix Design Summary

NDOT Concrete Mix Design – Full Summary (1 yd³ of Concrete)
Project Number: 3 | Class: 47BD | Control No: 2
-------------------------------------------------------------

              Component Weight (lb/yd³)          Notes
0                Cement           580.0
1                 Water           299.2
2        Fine Aggregate          1113.3
3      Coarse Aggregate          1701.5
4       Other Aggregate             0.0
5      Air (volumetric)           6.5 %  percent / ft³
6  Total (sanity check)          3694.0

### Scenario 3: 47B-HE
- **Source:** NDOT Pavement Design Manual
- **Use case:** Rapid Pavement Repairs, cold weather, fast track projects, and early form removal
- **Inputs:**
  - cement_A (lb/ft^3)= 700
  - fly_ash_B (lb/ft^3) = 60
  - silica_fume_C (lb/ft^3) = 20
  - other_scm_D (lb/ft^3) = 0
  - wc_ratio_E = 0.38
  - target_air_content_F (%) = 6.0
  - G_percent_fine_aggregate (%) = 43
  - H_percent_coarse_aggregate (%) = 57
  - I_percent_other_aggregate (%) = 0
  - sg_cement_J = 3.15
  - sg_fly_ash_K = 2.40
  - sg_silica_fume_L = 2.20
  - sg_other_scm_M = 2.80
  - N_specific_gravity = 2.65
  - O_specific_gravity = 2.70
  - P_specific_gravity = 2.70

In [54]:
ndot_mix_design()

=== NDOT Concrete Mix Design ===

Enter project number:  3
Enter control number:  3
Enter class of concrete:  47B-HE
Enter weight of cement per yd^3:  700
Enter weight of fly ash per yd^3:  60
Enter weight of silica fume per yd^3:  20
Enter weight of other SCM per yd^3:  0
Enter targer water/cement ratio:  0.38
Enter targer % air content:  6
Enter targer % fine aggregate:  43
Enter targer % coarse aggregate:  57
Enter targer % other aggregate:  0
Enter specific gravity of cement J:  3.15
Enter specific gravity of cement K:  2.40
Enter specific gravity of cement L:  2.20
Enter specific gravity of cement M:  2.80
Enter specific gravity of cement N:  2.65
Enter specific gravity of cement O:  2.70
Enter specific gravity of cement P:  2.70

---------------------------------------------
 NDOT Concrete Mix Design – Weight Summary
         (1 Cubic Yard of Concrete)
---------------------------------------------
Project Number:       3
Class of Concrete:    47B-HE
Control Number:       3
---------------------------------------------
Cement (A):               700.0 lb
Fly Ash (B):               60.0 lb
Silica Fume (C):           20.0 lb
Other SCM (D):              0.0 lb
---------------------------------------------
Fine Aggregate (Y):        1175 lb
Coarse Aggregate (Z):      1587 lb
Other Aggregate (AA):         0 lb
---------------------------------------------
Water (Q):                  296 lb
---------------------------------------------
End of Mix Design Summary

NDOT Concrete Mix Design – Full Summary (1 yd³ of Concrete)
Project Number: 3 | Class: 47B-HE | Control No: 3
-------------------------------------------------------------

              Component Weight (lb/yd³)          Notes
0                Cement           700.0
1                 Water           296.4
2        Fine Aggregate          1174.8
3      Coarse Aggregate          1586.7
4       Other Aggregate             0.0
5      Air (volumetric)           6.0 %  percent / ft³
6  Total (sanity check)          3757.9

### Scenario 4: 47B-OL
- **Source:** NDOT Pavement Design Manual
- **Use case:** Interstate pavements, high-traffic, industrial/freight corridors, and airport pavements
- **Inputs:**
  - cement_A (lb/ft^3)= 520
  - fly_ash_B (lb/ft^3) = 80
  - silica_fume_C (lb/ft^3) = 0
  - other_scm_D (lb/ft^3) = 0
  - wc_ratio_E = 0.35
  - target_air_content_F (%) = 5.5
  - G_percent_fine_aggregate (%) = 40
  - H_percent_coarse_aggregate (%) = 60
  - I_percent_other_aggregate (%) = 0
  - sg_cement_J = 3.15
  - sg_fly_ash_K = 2.40
  - sg_silica_fume_L = 2.20
  - sg_other_scm_M = 2.80
  - N_specific_gravity = 2.65
  - O_specific_gravity = 2.70
  - P_specific_gravity = 2.70

In [17]:
ndot_mix_design()

=== NDOT Concrete Mix Design ===

Enter project number:  3
Enter control number:  4
Enter class of concrete:  47B-OL
Enter weight of cement per yd^3:  520
Enter weight of fly ash per yd^3:  80
Enter weight of silica fume per yd^3:  0
Enter weight of other SCM per yd^3:  0
Enter targer water/cement ratio:  0.35
Enter targer % air content:  5.5
Enter targer % fine aggregate:  40
Enter targer % coarse aggregate:  60
Enter targer % other aggregate:  0
Enter specific gravity of cement J:  3.15
Enter specific gravity of cement K:  2.40
Enter specific gravity of cement L:  2.20
Enter specific gravity of cement M:  2.80
Enter specific gravity of cement N:  2.65
Enter specific gravity of cement O:  2.70
Enter specific gravity of cement P:  2.70

---------------------------------------------
 NDOT Concrete Mix Design – Weight Summary
         (1 Cubic Yard of Concrete)
---------------------------------------------
Project Number:       3
Class of Concrete:    47B-OL
Control Number:       4
---------------------------------------------
Cement (A):               520.0 lb
Fly Ash (B):               80.0 lb
Silica Fume (C):            0.0 lb
Other SCM (D):              0.0 lb
---------------------------------------------
Fine Aggregate (Y):        1255 lb
Coarse Aggregate (Z):      1918 lb
Other Aggregate (AA):         0 lb
---------------------------------------------
Water (Q):                  210 lb
---------------------------------------------
End of Mix Design Summary

NDOT Concrete Mix Design – Full Summary (1 yd³ of Concrete)
Project Number: 3 | Class: 47B-OL | Control No: 4
-------------------------------------------------------------

              Component Weight (lb/yd³)          Notes
0                Cement           520.0
1                 Water           210.0
2        Fine Aggregate          1254.7
3      Coarse Aggregate          1917.6
4       Other Aggregate             0.0
5      Air (volumetric)           5.5 %  percent / ft³
6  Total (sanity check)          3902.4